# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'HomeWork03' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HomeWork03
  pod 'Alamofire', '~> 4.5'
  pod 'SDWebImage', '~> 4.0'
	

end
